name: clinic_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  alphabet_list_scroll_view: ^2.0.0
  animate_do: ^2.0.0
  animations: ^2.0.2
  app_settings: null
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dot_navigation_bar: null
  equatable: null
  expansion_tile_card: ^2.0.0
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_contacts: 1.1.1+2
  flutter_keyboard_visibility: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.3.2
  flutter_slidable: ^1.1.0
  flutter_typeahead: ^3.2.4
  flutter_vector_icons: ^1.0.0
  images_picker: null
  intl: ^0.17.0
  parse_server_sdk_flutter: ^3.1.0
  syncfusion_flutter_calendar: ^19.4.38
  url_launcher: ^6.0.9
  freezed_annotation:
dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: null
  freezed:

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: pierSans
      fonts:
        - asset: assets/fonts/PierSans-Regular.otf
    - family: merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
