name: clinic_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  animations: ^2.0.2
  app_settings: null
  auto_size_text: ^3.0.0
  # bitsdojo_window: ^0.1.1
  cupertino_icons: ^1.0.2
  time_range_picker: ^2.1.0
  dot_navigation_bar: null
  equatable: null
  expansion_tile_card: ^2.0.0
  fluent_ui: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_contacts: ^1.1.3
  flutter_keyboard_visibility: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_slidable: ^2.0.0
  flutter_vector_icons: ^1.0.0
  images_picker: null
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^20.1.50
  url_launcher: ^6.0.9
  window_manager: ^0.2.1 
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  drift: ^2.1.0
  path: ^1.8.0
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.9
  platform_device_id: ^1.0.1
  logger: ^1.1.0
  extended_masked_text: ^2.3.1
#  drift: ^2.1.0
#  sqlite3_flutter_libs: ^0.5.0
#  path_provider: ^2.0.0
#  path: ^1.8.2

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: null
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
#  _fe_analyzer_shared: 31.0.0
  mockito: null
  drift_dev: ^2.1.0

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: pierSans
      fonts:
        - asset: assets/fonts/PierSans-Regular.otf
    - family: merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
