// Mocks generated by Mockito 5.0.17 from annotations
// in clinic_v2/test/app/features/auth/auth_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:clinic_v2/core/common/models/custom_response.dart' as _i2;
import 'package:clinic_v2/core/common/utilities/enums.dart' as _i6;
import 'package:clinic_v2/core/features/authentication/domain/auth_domain.dart'
    as _i4;
import 'package:clinic_v2/core/features/users/domain/src/entities/base_server_user.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCustomResponse_0<T> extends _i1.Fake
    implements _i2.CustomResponse<T> {}

/// A class which mocks [BaseAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseAuthRepository<T extends _i3.BaseServerUser> extends _i1.Mock
    implements _i4.BaseAuthRepository<T> {
  MockBaseAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentUser(T? _currentUser) =>
      super.noSuchMethod(Invocation.setter(#currentUser, _currentUser),
          returnValueForMissingStub: null);
  @override
  _i5.Future<bool> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i2.CustomResponse<_i2.NoResult>> loadCurrentUser() =>
      (super.noSuchMethod(Invocation.method(#loadCurrentUser, []),
              returnValue: Future<_i2.CustomResponse<_i2.NoResult>>.value(
                  _FakeCustomResponse_0<_i2.NoResult>()))
          as _i5.Future<_i2.CustomResponse<_i2.NoResult>>);
  @override
  bool hasLoggedInUser() =>
      (super.noSuchMethod(Invocation.method(#hasLoggedInUser, []),
          returnValue: false) as bool);
  @override
  _i5.Future<_i2.CustomResponse<_i2.NoResult>> resetUserPassword(
          String? emailAddress) =>
      (super.noSuchMethod(Invocation.method(#resetUserPassword, [emailAddress]),
              returnValue: Future<_i2.CustomResponse<_i2.NoResult>>.value(
                  _FakeCustomResponse_0<_i2.NoResult>()))
          as _i5.Future<_i2.CustomResponse<_i2.NoResult>>);
  @override
  _i5.Future<_i2.CustomResponse<_i2.NoResult>> logoutUser() =>
      (super.noSuchMethod(Invocation.method(#logoutUser, []),
              returnValue: Future<_i2.CustomResponse<_i2.NoResult>>.value(
                  _FakeCustomResponse_0<_i2.NoResult>()))
          as _i5.Future<_i2.CustomResponse<_i2.NoResult>>);
  @override
  _i5.Future<_i2.CustomResponse<_i2.NoResult>> login(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #login, [], {#username: username, #password: password}),
              returnValue: Future<_i2.CustomResponse<_i2.NoResult>>.value(
                  _FakeCustomResponse_0<_i2.NoResult>()))
          as _i5.Future<_i2.CustomResponse<_i2.NoResult>>);
  @override
  _i5.Future<_i2.CustomResponse<_i2.NoResult>> signUp(
          {String? emailAddress,
          String? username,
          String? password,
          _i6.UserRole? role}) =>
      (super.noSuchMethod(
              Invocation.method(#signUp, [], {
                #emailAddress: emailAddress,
                #username: username,
                #password: password,
                #role: role
              }),
              returnValue: Future<_i2.CustomResponse<_i2.NoResult>>.value(
                  _FakeCustomResponse_0<_i2.NoResult>()))
          as _i5.Future<_i2.CustomResponse<_i2.NoResult>>);
  @override
  _i5.Future<_i2.CustomResponse<_i2.NoResult>> addNewUserInfoByAdmin(
          {String? emailAddress, _i6.UserRole? userRole}) =>
      (super.noSuchMethod(
              Invocation.method(#addNewUserInfoByAdmin, [],
                  {#emailAddress: emailAddress, #userRole: userRole}),
              returnValue: Future<_i2.CustomResponse<_i2.NoResult>>.value(
                  _FakeCustomResponse_0<_i2.NoResult>()))
          as _i5.Future<_i2.CustomResponse<_i2.NoResult>>);
}

/// A class which mocks [BaseServerUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseServerUser extends _i1.Mock implements _i3.BaseServerUser {
  MockBaseServerUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get email =>
      (super.noSuchMethod(Invocation.getter(#email), returnValue: '')
          as String);
  @override
  _i6.UserRole get role => (super.noSuchMethod(Invocation.getter(#role),
      returnValue: _i6.UserRole.admin) as _i6.UserRole);
}
