// Mocks generated by Mockito 5.3.1 from annotations
// in clinic_v2/test/unit/blocs/user_preferences_cubit/utils/user_preferences_repository_mock_factory.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i3;

import 'package:clinic_v2/shared/models/result/result.dart' as _i1;
import 'package:clinic_v2/domain/user_preferences/base/base_user_preferences.dart'
    as _i4;
import 'package:clinic_v2/domain/user_preferences/base/base_user_preferences_repository.dart'
    as _i5;
import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<V extends Object, E extends _i1.BasicError>
    extends _i2.SmartFake implements _i1.Result<V, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_1 extends _i2.SmartFake implements _i3.Locale {
  _FakeLocale_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseUserPreferences_2 extends _i2.SmartFake
    implements _i4.BaseUserPreferences {
  _FakeBaseUserPreferences_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseUserPreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseUserPreferencesRepository<T extends _i4.BaseUserPreferences>
    extends _i2.Mock implements _i5.BaseUserPreferencesRepository<T> {
  @override
  _i6.Future<dynamic> onInit() => (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
  @override
  _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>> setUserPreferences(
    _i7.ThemeMode? themeMode,
    _i3.Locale? locale,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserPreferences,
          [
            themeMode,
            locale,
          ],
        ),
        returnValue:
            _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
          this,
          Invocation.method(
            #setUserPreferences,
            [
              themeMode,
              locale,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
          this,
          Invocation.method(
            #setUserPreferences,
            [
              themeMode,
              locale,
            ],
          ),
        )),
      ) as _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>);
  @override
  _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>> loadUserPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadUserPreferences,
          [],
        ),
        returnValue:
            _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
          this,
          Invocation.method(
            #loadUserPreferences,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
          this,
          Invocation.method(
            #loadUserPreferences,
            [],
          ),
        )),
      ) as _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>);
  @override
  _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>
      updateUserThemePreference(_i7.ThemeMode? themeMode) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateUserThemePreference,
              [themeMode],
            ),
            returnValue:
                _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                    _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
              this,
              Invocation.method(
                #updateUserThemePreference,
                [themeMode],
              ),
            )),
            returnValueForMissingStub:
                _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                    _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
              this,
              Invocation.method(
                #updateUserThemePreference,
                [themeMode],
              ),
            )),
          ) as _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>);
  @override
  _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>
      updateUserLocalePreference(_i3.Locale? locale) => (super.noSuchMethod(
            Invocation.method(
              #updateUserLocalePreference,
              [locale],
            ),
            returnValue:
                _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                    _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
              this,
              Invocation.method(
                #updateUserLocalePreference,
                [locale],
              ),
            )),
            returnValueForMissingStub:
                _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>.value(
                    _FakeResult_0<_i1.VoidValue, _i1.BasicError>(
              this,
              Invocation.method(
                #updateUserLocalePreference,
                [locale],
              ),
            )),
          ) as _i6.Future<_i1.Result<_i1.VoidValue, _i1.BasicError>>);
}
