// Mocks generated by Mockito 5.3.1 from annotations
// in clinic_v2/test/unit/blocs/auth_bloc/utils/mock_auth_repository_factory.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:clinic_v2/shared/models/result/result.dart' as _i1;
import 'package:clinic_v2/app/features/authentication/domain/base_auth_repository.dart'
    as _i4;
import 'package:clinic_v2/domain/authentication/base/base_server_user.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<V extends Object, E extends _i1.AppError>
    extends _i2.SmartFake implements _i1.Result<V, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseAuthRepository<U extends _i3.BaseServerUser> extends _i2.Mock
    implements _i4.BaseAuthRepository<U> {
  @override
  _i5.Stream<U?> get usersStream => (super.noSuchMethod(
        Invocation.getter(#usersStream),
        returnValue: _i5.Stream<U?>.empty(),
        returnValueForMissingStub: _i5.Stream<U?>.empty(),
      ) as _i5.Stream<U?>);
  @override
  _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>> onInit() =>
      (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
            _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #onInit,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #onInit,
            [],
          ),
        )),
      ) as _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>);
  @override
  _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>> register({
    required String? email,
    required String? name,
    required String? phoneNumber,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #name: name,
            #phoneNumber: phoneNumber,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
            _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #name: name,
              #phoneNumber: phoneNumber,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #name: name,
              #phoneNumber: phoneNumber,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>);
  @override
  _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
            _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>);
  @override
  _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>> requestPasswordReset(
          String? emailAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [emailAddress],
        ),
        returnValue: _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
            _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #requestPasswordReset,
            [emailAddress],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #requestPasswordReset,
            [emailAddress],
          ),
        )),
      ) as _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>);
  @override
  _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>
      requestVerificationEmail() => (super.noSuchMethod(
            Invocation.method(
              #requestVerificationEmail,
              [],
            ),
            returnValue:
                _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                    _FakeResult_0<_i1.VoidValue, _i1.AppError>(
              this,
              Invocation.method(
                #requestVerificationEmail,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                    _FakeResult_0<_i1.VoidValue, _i1.AppError>(
              this,
              Invocation.method(
                #requestVerificationEmail,
                [],
              ),
            )),
          ) as _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>);
  @override
  _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>> logout() =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
            _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>.value(
                _FakeResult_0<_i1.VoidValue, _i1.AppError>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i5.Future<_i1.Result<_i1.VoidValue, _i1.AppError>>);
}
